# constants_countries.py
# List of countries with their ISO code and calling code
# You can extend or modify this as needed.

COUNTRIES = [
    {"name": "India", "iso_code": "IN", "country_code": "+91"},
    {"name": "United States", "iso_code": "US", "country_code": "+1"},
    {"name": "United Kingdom", "iso_code": "GB", "country_code": "+44"},
    {"name": "Canada", "iso_code": "CA", "country_code": "+1"},
    {"name": "Australia", "iso_code": "AU", "country_code": "+61"},
    {"name": "Singapore", "iso_code": "SG", "country_code": "+65"},
    {"name": "United Arab Emirates", "iso_code": "AE", "country_code": "+971"},
    {"name": "Germany", "iso_code": "DE", "country_code": "+49"},
    {"name": "France", "iso_code": "FR", "country_code": "+33"},
    {"name": "Italy", "iso_code": "IT", "country_code": "+39"},
    {"name": "Spain", "iso_code": "ES", "country_code": "+34"},
    {"name": "Netherlands", "iso_code": "NL", "country_code": "+31"},
    {"name": "Brazil", "iso_code": "BR", "country_code": "+55"},
    {"name": "South Africa", "iso_code": "ZA", "country_code": "+27"},
    {"name": "New Zealand", "iso_code": "NZ", "country_code": "+64"},
    {"name": "Japan", "iso_code": "JP", "country_code": "+81"},
    {"name": "China", "iso_code": "CN", "country_code": "+86"},
    {"name": "Nepal", "iso_code": "NP", "country_code": "+977"},
    {"name": "Bangladesh", "iso_code": "BD", "country_code": "+880"},
    {"name": "Sri Lanka", "iso_code": "LK", "country_code": "+94"},
    {"name": "Pakistan", "iso_code": "PK", "country_code": "+92"},
    {"name": "Saudi Arabia", "iso_code": "SA", "country_code": "+966"},
    {"name": "Qatar", "iso_code": "QA", "country_code": "+974"},
    {"name": "Kuwait", "iso_code": "KW", "country_code": "+965"},
    {"name": "Oman", "iso_code": "OM", "country_code": "+968"},
    {"name": "Malaysia", "iso_code": "MY", "country_code": "+60"},
    {"name": "Indonesia", "iso_code": "ID", "country_code": "+62"},
    {"name": "Philippines", "iso_code": "PH", "country_code": "+63"},
    {"name": "Thailand", "iso_code": "TH", "country_code": "+66"},
    {"name": "Vietnam", "iso_code": "VN", "country_code": "+84"},
    {"name": "Nigeria", "iso_code": "NG", "country_code": "+234"},
    {"name": "Kenya", "iso_code": "KE", "country_code": "+254"},
    {"name": "Egypt", "iso_code": "EG", "country_code": "+20"},
    {"name": "Turkey", "iso_code": "TR", "country_code": "+90"},
    {"name": "Mexico", "iso_code": "MX", "country_code": "+52"},
    {"name": "Argentina", "iso_code": "AR", "country_code": "+54"},
    {"name": "Russia", "iso_code": "RU", "country_code": "+7"},
    {"name": "South Korea", "iso_code": "KR", "country_code": "+82"},
    {"name": "Hong Kong", "iso_code": "HK", "country_code": "+852"},
    {"name": "Switzerland", "iso_code": "CH", "country_code": "+41"},
]
